#pragma once

#define BIRD_SIZE 50
#define OBSTACLE_BRICK_SIZE 49.5f	// Because the bird bricks cannot perfectly align with the obstacle bricks due to the physics engine

#define OBSTACLE_SPEED 100

#define BIRD_COLLISION_BITMASK 0x00000001
#define EGG_COLLISION_BITMASK 0x00000002
#define NORMAL_OBSTACLE_COLLISION_BITMASK 0x00000003
#define SPIKE_OBSTACLE_COLLISION_BITMASK 0x00000004
#define GARBAGE_COLLECTION_COLLISION_BITMASK 0x00000005

#define OBSTACLE_SPAWN_INTERVAL 3.5f
#define LOWEST_OBSTACLE_HEIGHT 225
#define HIGHEST_OBSTACLE_HEIGHT 625
#define MAX_OBSTACLE_BRICKS_PER_GROUP 5
#define MIN_OBSTACLE_BRICKS_PER_GROUP 2
